### ISSUE TITLE
Feature request: SD card instead of USB flash?

### ISSUE THREAD

**Issue by jgetas** [jumpstarter-dev/dutlink-board#1]
Hi - I saw your talk as FOSDEM24 stream. Absolutely amazing!
For our HW-boards-in-the-loop we would need SD cards instead of USB flash devices because they usually have an eMMC/SD Card primary boot device interface. Ideally, the DUTboard would have an SD card slot which should be switchable between host and test board. Do you think something like that would be possible with the jumpstarter HW + SW?

**Comment by jgetas** [comment]
I am SW guy, but maybe utilizing a QSPI switch https://www.ti.com/lit/ds/symlink/ts3a27518e.pdf with a USB SD card controller IC could serve this request:
```
+--------+        +--------+        +--------+
|  µSD  -- - - - -|  QSPI  | - - - -| USB-SD | - - - - USB Hub / Host
| Card  -- - - - -|   MUX  | - - - -|  CTRL  |
+--------+        +--------+        +--------+
                      | |
                   DUT Board
                  µSD interface
```
The µSD (QSPI) MUX could be switched either automatically with the USB Hub switch or by some custom jumpstarter command.

@mangelajo @oglok : Would you think this is feasible and a valid feature enhancement which you would pick up or would you consider this more like something to put somewhere down in the backlog instead 😄 ?

**Comment by oglok** [comment]
Hi @jgetas !! Thanks for the feedback, this is really great.
During the talk, we spoke about drivers. Our reference driver is this, the dutlink board, but we also showcased another option  of a hardware connector: sdwire mux + serial-to-usb cable + smartplug

In this PR you can see the code: https://github.com/jumpstarter-dev/jumpstarter/pull/8

Would this work for you? We could certainly help with a deep dive on how it works and how it should be used.

**Comment by jgetas** [comment]
Hi @oglok - ah I heard the term "sdwire" in the talk but actually did not really know what it is. That's maybe really a solution. I personally would much more love it if the board would support it out of the box because it's the standard use case we have in our team in our company. I'll see what we could do about it. 
Thanks - I'll close this topic (for now... 😉)

**Comment by mangelajo** [comment]
> Hi @oglok - ah I heard the term "sdwire" in the talk but actually did not really know what it is. That's maybe really a solution. I personally would much more love it if the board would support it out of the box because it's the standard use case we have in our team in our company. I'll see what we could do about it. Thanks - I'll close this topic (for now... 😉)

https://shop.3mdeb.com/shop/open-source-hardware/sdwire/

This is the one we are enabling in that PR, I need to document it better.

The driver on the PR makes the jumpstarter work without the DUTLink, but I want to add another version that makes dutlink+sdwire work together too.

@jgetas I'd love to know more about your use cases and your plans. Since the presentation I have started looking at LabGrid because I was not aware of the project. It's a bit more complicated than jumpstarter. But I am wondering if we could instead collaborate with them to make it easier to use (i.e. with github, etc), and of course provide support for the dutlink.
